apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/multi-document-rag-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: gcr.io/multi-doc-rag/backend:latest
          name: multi-doc-rag-backend
          ports:
            - containerPort: 8005
              hostPort: 8005
              protocol: TCP
      restartPolicy: Always
