version: '3'
services:
  frontend:
    container_name: multi-doc-rag-frontend
    build:
      context: ./frontend/document-chatbot
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: multi-doc-rag-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    depends_on:
      - mongodb
      - chroma

  mongodb:
    container_name: multi-doc-rag-mongodb
    image: mongo:latest
    ports:
      - '27017:27017'

  chroma:
    container_name: multi-doc-rag-chroma
    build:
      context: ./chroma
      dockerfile: Dockerfile
    ports:
      - '8000:8000'