version: '3.8'
services:
  mongodb:
    container_name: multi-doc-rag-mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_volume:/data/db

  chroma:
    container_name: multi-doc-rag-chroma
    build:
      context: ./chroma
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - chroma_volume:/data/chroma  # Ensure this is the correct path

  backend:
    container_name: multi-doc-rag-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    depends_on:
      - mongodb
      - chroma
    volumes:
      - ./backend:/app

  frontend:
    container_name: multi-doc-rag-frontend
    build:
      context: ./frontend/document-chatbot
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend/document-chatbot:/app

volumes:
  mongo_volume:
  chroma_volume: